#!/usr/bin/env python3
"""Build every generated page of tokenwave.ai from data/.

Single sources of truth:
    data/benchmarks/<slug>.json   scraped benchmark records (tools/scrape.py)
    data/models.json              model id -> {name, org, color}
    data/focus_en.json            English overrides for Chinese source fields
    data/featured.json            curated cards for the benchmarks list page
    data/blog/<slug>.json         hand-polished article copy

Outputs:
    benchmarks/<slug>.html  x48       blog/<slug>.html  x8
    benchmarks.html                   blog.html
    compare.html                      static/js/compare-app.js
    data/compare.json                 sitemap.xml, robots.txt

Deterministic and idempotent: re-running with unchanged data produces
byte-identical output (verify with `git diff` / checksums).

Run:  python3 tools/build.py
"""

import html as htmlmod
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
TPL = Path(__file__).resolve().parent / "templates"

SITE = "https://tokenwave.ai"
DOMAIN_ORDER = ["agent", "multimodal", "aigc", "llm"]
DOMAIN_SHORT = {"agent": "Agent", "multimodal": "MLLM", "aigc": "AIGC", "llm": "LLM"}

GEN_NOTE = "<!-- Generated by tools/build.py — edit data/ or tools/, not this file. -->"


def esc(s):
    return htmlmod.escape(str(s), quote=True)


def fmt_score(v):
    return f"{v:g}" if isinstance(v, (int, float)) else "–"


# ── data loading ─────────────────────────────────────────────────────────────

def load():
    benches = {}
    for f in sorted((DATA / "benchmarks").glob("*.json")):
        d = json.loads(f.read_text(encoding="utf-8"))
        benches[d["slug"]] = d

    focus_en = json.loads((DATA / "focus_en.json").read_text(encoding="utf-8"))
    for slug, over in focus_en.items():
        if slug.startswith("_") or slug not in benches:
            continue
        g = benches[slug]["at_a_glance"]
        if over.get("focus"):
            g["focus"] = over["focus"]
        if over.get("setting"):
            g["setting"] = over["setting"]

    models = json.loads((DATA / "models.json").read_text(encoding="utf-8"))
    featured = json.loads((DATA / "featured.json").read_text(encoding="utf-8"))["featured"]

    posts = []
    for f in sorted((DATA / "blog").glob("*.json")):
        posts.append(json.loads(f.read_text(encoding="utf-8")))
    posts.sort(key=lambda p: p["date"], reverse=True)

    editorial = {}
    ed_dir = DATA / "editorial"
    if ed_dir.exists():
        for f in sorted(ed_dir.glob("*.json")):
            e = json.loads(f.read_text(encoding="utf-8"))
            editorial[e["slug"]] = e

    return benches, models, featured, posts, editorial


# ── shared page chrome ───────────────────────────────────────────────────────

def head(depth, title, desc, path, og_type="website", published=None):
    d = depth
    og_extra = ""
    if published:
        og_extra = f'\n    <meta property="article:published_time" content="{published}">'
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{esc(title)}</title>
    <meta name="description" content="{esc(desc)}">

    <meta property="og:type" content="{og_type}">
    <meta property="og:site_name" content="TokenWave AI">
    <meta property="og:title" content="{esc(title)}">
    <meta property="og:description" content="{esc(desc)}">
    <meta property="og:url" content="{SITE}/{path}">
    <meta property="og:image" content="{SITE}/static/images/og-default.png">{og_extra}
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="{esc(title)}">
    <meta name="twitter:description" content="{esc(desc)}">
    <meta name="twitter:image" content="{SITE}/static/images/og-default.png">
    <link rel="canonical" href="{SITE}/{path}">

    <link rel="icon" type="image/svg+xml" href="{d}static/favicon.svg">
    <link rel="icon" type="image/png" sizes="192x192" href="{d}static/favicon-192.png">
    <link rel="apple-touch-icon" href="{d}static/apple-touch-icon.png">
    <link rel="preload" href="{d}static/fonts/IBMPlexSans-Regular.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="{d}static/fonts/IBMPlexMono-Regular.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="stylesheet" href="{d}static/css/style.css">
    <!-- Pre-hide page if arriving via full-page transition (must run before first paint) -->
    <script>try{{if(sessionStorage.getItem('tokenwave_transition')==='full'){{document.documentElement.style.opacity='0';}}}}catch(e){{}}</script>
</head>"""


def header(depth, active):
    d = depth
    def nav(href, label, key):
        cls = ' class="active"' if key == active else ""
        return f'<a href="{d}{href}"{cls}>{label}</a>'
    return f"""<body>
    <header class="site-header">
        <div class="container header-content">
            <a class="logo" href="{d}index.html" aria-label="TokenWave AI home">
                <img src="{d}static/images/logo.jpg" alt="TokenWave AI" class="logo-icon">
            </a>
            <nav>
                {nav('index.html', 'Home', 'home')}
                {nav('blog.html', 'Blog', 'blog')}
                {nav('benchmarks.html', 'Benchmarks', 'benchmarks')}
                {nav('compare.html', 'Compare', 'compare')}
                {nav('joinus.html', 'Join Us', 'joinus')}
            </nav>
        </div>
    </header>
    <main class="container">
"""


def footer(depth):
    d = depth
    return f"""
    </main>
    <footer class="site-footer">
        <div class="container footer-grid">
            <div class="footer-brand">
                <div class="footer-wordmark">TokenWave AI</div>
                <p>Charting the frontier of AI with transparent, comparable benchmarks.</p>
                <p>&copy; 2026 TokenWave AI</p>
            </div>
            <div class="footer-col">
                <div class="h">Site</div>
                <a href="{d}index.html">Home</a>
                <a href="{d}blog.html">Blog</a>
                <a href="{d}benchmarks.html">Benchmarks</a>
                <a href="{d}compare.html">Compare</a>
                <a href="{d}joinus.html">Join Us</a>
            </div>
            <div class="footer-col">
                <div class="h">Contact</div>
                <a href="mailto:contact@tokenwave.ai">contact@tokenwave.ai</a>
                <a href="mailto:hr@tokenwave.ai">hr@tokenwave.ai</a>
                <a href="https://x.com/" target="_blank" rel="noopener noreferrer" class="social-link" aria-label="Follow us on X">
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/>
                    </svg>
                </a>
            </div>
        </div>
    </footer>
    <!-- Three.js particle background (bundled locally) -->
    <script src="{d}static/js/three.min.js" defer></script>
    <script src="{d}static/js/particles.js" defer></script>
    <!-- Page transition state machine -->
    <script src="{d}static/js/transition.js" defer></script>
</body>
</html>
"""


def write(rel, content):
    out = ROOT / rel
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")


# ── shared fragments ─────────────────────────────────────────────────────────

def file_slug(slug):
    return slug.replace("_", "-")


def leader_of(b):
    lb = b["leaderboard"]
    return lb[0] if lb else None


def bench_meta_line(b):
    lead = leader_of(b)
    bits = []
    if lead:
        bits.append(f'<span class="lead">🏆 {esc(lead["model"])}: {fmt_score(lead["score"])}</span>')
    bits.append(esc(b["subcategory"]))
    updated = b["at_a_glance"].get("data_updated")
    if updated:
        bits.append(f"updated {esc(updated)}")
    return '\n                <span class="sep">·</span>\n                '.join(bits)


def card(depth, href, image, meta_html, title, blurb_html):
    return f"""
    <article class="card card-row">
        <div class="card-image" style="background-image: url('{depth}{image}');"></div>
        <div class="card-body">
            <div class="card-meta">
                {meta_html}
            </div>
            <h3><a href="{href}">{esc(title)}</a></h3>
            <p>{blurb_html}</p>
        </div>
    </article>
"""


def leaderboard_table(b, top=None, depth=""):
    metric = b.get("leaderboard_metric") or "Score"
    rows = b["leaderboard"][:top] if top else b["leaderboard"]
    has_date = any(r.get("date") for r in rows)
    head_cells = f"<th>#</th><th>Model</th><th>{esc(metric)}</th><th>Source</th>"
    if has_date:
        head_cells += "<th>Date</th>"
    out = [f"<table class=\"data-table\">\n            <thead>\n                <tr>{head_cells}</tr>\n            </thead>\n            <tbody>"]
    src_label = {"official": "Official", "community": "Community", "self_reported": "Self-reported"}
    for r in rows:
        cls = ' class="lead-row"' if r["rank"] == 1 else ""
        cells = [
            f'<td><span class="rank">{r["rank"]}</span></td>',
            f'<td>{esc(r["model"])}</td>',
            f'<td class="num">{fmt_score(r["score"])}</td>',
            f'<td>{esc(src_label.get(r.get("source"), r.get("source") or "–"))}</td>',
        ]
        if has_date:
            cells.append(f'<td class="num">{esc(r.get("date") or "–")}</td>')
        out.append(f"                <tr{cls}>{''.join(cells)}</tr>")
    out.append("            </tbody>\n        </table>")
    return "\n".join(out)


# ── benchmark detail pages ───────────────────────────────────────────────────

# Sticky-TOC scroll spy (plain string — not an f-string — because of the braces)
SCROLLSPY = """<script>
(function () {
    var toc = document.querySelector('.toc');
    if (!toc || !('IntersectionObserver' in window)) return;
    var links = {};
    toc.querySelectorAll('a[href^="#"]').forEach(function (a) {
        links[a.getAttribute('href').slice(1)] = a;
    });
    var io = new IntersectionObserver(function (entries) {
        entries.forEach(function (e) {
            if (!e.isIntersecting) return;
            Object.keys(links).forEach(function (k) { links[k].classList.remove('on'); });
            var l = links[e.target.id];
            if (l) l.classList.add('on');
        });
    }, { rootMargin: '-15% 0px -70% 0px' });
    Object.keys(links).forEach(function (k) {
        var el = document.getElementById(k);
        if (el) io.observe(el);
    });
})();
</script>"""


def build_detail(b, post_by_bench, editorial):
    d = "../"
    fs = file_slug(b["slug"])
    g = b["at_a_glance"]
    ed = editorial.get(b["slug"])
    desc = (ed["tagline"] + "." if ed else
            (b["abstract"][:250].strip() if b["abstract"] else f"{b['name']} on TokenWave AI."))

    actions = []
    if b["links"].get("paper"):
        actions.append(f'<a class="button primary" href="{esc(b["links"]["paper"])}" target="_blank" rel="noopener noreferrer">Paper ↗</a>')
    if b["links"].get("code") and b["links"].get("code") != b["links"].get("paper"):
        actions.append(f'<a class="button" href="{esc(b["links"]["code"])}" target="_blank" rel="noopener noreferrer">Code &amp; Website ↗</a>')
    if b["links"].get("pdf"):
        actions.append(f'<a class="button" href="{esc(b["links"]["pdf"])}" target="_blank" rel="noopener noreferrer">PDF ↗</a>')
    actions_html = ""
    if actions:
        actions_html = f'\n    <div class="detail-actions">{" ".join(actions)}</div>'

    def paras(texts):
        return "\n        ".join(f"<p>{esc(t)}</p>" for t in texts)

    # (anchor id, TOC title, body html) — TOC and h2 anchors come from this list
    secs = []

    if ed:
        secs.append(("overview", "Overview", paras(ed["overview"])))
        secs.append(("why-it-matters", "Why it matters", paras(ed["why"])))
    elif b["abstract"]:
        secs.append(("abstract", "Abstract", f"<p>{esc(b['abstract'])}</p>"))

    if b["contributions"]:
        items = "\n            ".join(f"<li>{esc(c)}</li>" for c in b["contributions"])
        secs.append(("contributions", "Contributions", f"<ul>\n            {items}\n        </ul>"))

    if b["method"]:
        items = "\n            ".join(f"<li>{esc(m)}</li>" for m in b["method"])
        secs.append(("method", "Method &amp; evaluation", f"<ul>\n            {items}\n        </ul>"))

    if b["metrics"]:
        parts = []
        for m in b["metrics"]:
            direction = "Higher is better" if m["direction"] == "higher" else "Lower is better"
            bits = [f"<b>{esc(m['name'])}</b> &mdash; {direction}."]
            if m.get("note"):
                bits.append(esc(m["note"]))
            if m.get("range"):
                bits.append(f"Score range: {esc(m['range'])}.")
            parts.append(f"<p>{' '.join(bits)}</p>")
        secs.append(("metrics", "Evaluation metrics", "\n        ".join(parts)))

    if b["leaderboard"]:
        lb_note = f"<p>{esc(b['leaderboard_note'])}</p>\n        " if b.get("leaderboard_note") else ""
        secs.append(("leaderboard", "Leaderboard", f"{lb_note}{leaderboard_table(b)}"))

    if ed:
        secs.append(("reading-the-results", "Reading the results", paras(ed["reading"])))

    if b.get("figures"):
        figs = []
        for f in b["figures"]:
            figs.append(
                f'<figure>\n            <img src="{d}{esc(f["image"])}" alt="{esc(f["caption"] or b["name"] + " figure")}" loading="lazy">\n'
                f'            <figcaption>{esc(f["caption"])}</figcaption>\n        </figure>'
            )
        secs.append(("paper-figures", "Paper figures", "\n        ".join(figs)))

    glance_rows = []
    for key, label in [("focus", "Focus"), ("primary_metric", "Primary metric"),
                       ("setting", "Displayed setting"), ("models_scored", "Models scored"),
                       ("data_updated", "Data updated")]:
        val = g.get(key)
        if val in (None, "", "None"):
            continue
        glance_rows.append(f'            <li><span class="k">{label}</span><span>{esc(val)}</span></li>')
    if glance_rows:
        secs.append(("at-a-glance", "At a glance",
                     "<ul class=\"glance\">\n" + "\n".join(glance_rows) + "\n        </ul>"))

    body_parts = [f'<h2 id="{sid}">{title}</h2>\n        {body}' for sid, title, body in secs]

    post = post_by_bench.get(b["slug"])
    if post:
        body_parts.append(f"""<div class="crosslink">
            <div>
                <p class="t">Read the research note</p>
                <p class="s">{esc(post['title'])}</p>
            </div>
            <a class="button primary" href="{d}blog/{post['slug']}.html">Read note →</a>
        </div>""")

    body_sections = "\n\n        ".join(body_parts)

    toc_html = ""
    if len(secs) >= 4:
        toc_links = "\n        ".join(f'<a href="#{sid}">{title}</a>' for sid, title, _ in secs)
        toc_html = f"""
    <nav class="toc" aria-label="On this page">
        <div class="toc-h">On this page</div>
        {toc_links}
    </nav>"""

    tagline_html = f'\n            <p class="detail-tagline">{esc(ed["tagline"])}.</p>' if ed else ""

    stats_html = ""
    if ed and ed.get("stats"):
        tiles = "\n        ".join(
            f'<div class="stat-tile"><div class="v">{esc(s["value"])}</div><div class="l">{esc(s["label"])}</div></div>'
            for s in ed["stats"]
        )
        stats_html = f"""
    <div class="stat-grid">
        {tiles}
    </div>
"""

    lead = leader_of(b)
    lead_alt = f"{b['name']} — led by {lead['model']} at {fmt_score(lead['score'])}" if lead else b["name"]

    html = f"""{head(d, f"{b['name']} | TokenWave AI", desc, f"benchmarks/{fs}.html")}
{GEN_NOTE}
{header(d, 'benchmarks')}
<article class="detail">
    <div class="detail-hero">
        <div class="detail-image" style="background-image: url('{d}{esc(b['image'])}');" role="img" aria-label="{esc(lead_alt)}"></div>
        <div class="detail-head">
            <div class="eyebrow">{esc(b['domain_name'])} · {esc(b['subcategory'])}</div>
            <h1>{esc(b['name'])}</h1>{tagline_html}
            <p class="detail-meta">
                {bench_meta_line(b)}
            </p>{actions_html}
        </div>
    </div>
{stats_html}    <div class="detail-layout">
    <div class="markdown">

        {body_sections}

        <p class="back-link"><a href="{d}benchmarks.html">&larr; Back to Benchmarks</a></p>
    </div>{toc_html}
    </div>
</article>
{SCROLLSPY}
{footer(d)}"""
    write(f"benchmarks/{fs}.html", html)


# ── benchmarks list page ─────────────────────────────────────────────────────

def build_benchmarks_page(benches, featured, models_tracked):
    d = ""
    cards = []
    for f in featured:
        b = benches[f["slug"]]
        fs = file_slug(b["slug"])
        meta = bench_meta_line(b)
        cards.append(card(d, f"benchmarks/{fs}.html", b["image"], meta, b["name"], f["blurb"]))

    groups = []
    for dom in DOMAIN_ORDER:
        group = sorted((b for b in benches.values() if b["domain"] == dom), key=lambda x: x["name"].lower())
        if not group:
            continue
        chips = []
        for b in group:
            fs = file_slug(b["slug"])
            lead = leader_of(b)
            sub = esc(b["subcategory"])
            if lead:
                sub += f' <span class="sep">·</span> 🏆 {fmt_score(lead["score"])}'
            chips.append(f"""        <a class="bench-chip" href="benchmarks/{fs}.html">
            <span class="name">{esc(b['name'])}</span>
            <span class="sub">{sub}</span>
        </a>""")
        domain_name = group[0]["domain_name"]
        groups.append(f"""    <div class="bench-group">
        <h2 class="bench-group-title">{esc(domain_name)} <span class="count">{len(group)}</span></h2>
        <div class="chip-grid">
{chr(10).join(chips)}
        </div>
    </div>""")

    n = len(benches)
    html = f"""{head(d, "Benchmarks | TokenWave AI", "Define the Frontier and Track the Acceleration.", "benchmarks.html")}
{GEN_NOTE}
{header(d, 'benchmarks')}
<section class="page-header">
    <div class="eyebrow">Benchmarks</div>
    <h1>Define the Frontier and Track the Acceleration.</h1>
    <p class="page-intro mono">{n} benchmarks · 4 domains · {models_tracked} models on leaderboards</p>
</section>

<section class="list">
{''.join(cards)}
</section>

<section class="bench-index">
    <div class="eyebrow">Full index</div>
{chr(10).join(groups)}
</section>
{footer(d)}"""
    write("benchmarks.html", html)


# ── blog ─────────────────────────────────────────────────────────────────────

def read_minutes(post):
    words = 0
    for blk in post["body"]:
        for key in ("text",):
            if blk.get(key):
                words += len(blk[key].split())
        for item in blk.get("items", []):
            words += len(item.split())
    words += len(post["summary"].split())
    return max(1, round(words / 200))


def build_blog_list(posts, benches):
    d = ""
    cards = []
    for p in posts:
        b = benches[p["benchmark"]]
        meta = (f'<span>{esc(p["date"])}</span>\n                '
                f'<span class="sep">·</span>\n                '
                f'<span class="pill">{esc(b["subcategory"])}</span>\n                '
                f'<span class="sep">·</span>\n                '
                f'<span>{read_minutes(p)} min read</span>')
        cards.append(card(d, f"blog/{p['slug']}.html", b["image"], meta, p["title"], p["summary"]))

    html = f"""{head(d, "Blog | TokenWave AI", "Science and Knowledge are Better when Shared.", "blog.html")}
{GEN_NOTE}
{header(d, 'blog')}
<section class="page-header">
    <div class="eyebrow">Blog</div>
    <h1>Science and Knowledge are Better when Shared.</h1>
    <p class="page-intro">Research notes from the TokenWave team &mdash; one benchmark, one finding at a time.</p>
</section>

<section class="list">
{''.join(cards)}
</section>
{footer(d)}"""
    write("blog.html", html)


def build_post(p, benches):
    d = "../"
    b = benches[p["benchmark"]]
    fs = file_slug(b["slug"])

    blocks = []
    blocks.append(f"<p>{p['summary']}</p>")
    for blk in p["body"]:
        t = blk["type"]
        if t == "p":
            blocks.append(f"<p>{blk['text']}</p>")
        elif t == "h2":
            blocks.append(f"<h2>{blk['text']}</h2>")
        elif t == "ul":
            items = "\n            ".join(f"<li>{i}</li>" for i in blk["items"])
            blocks.append(f"<ul>\n            {items}\n        </ul>")
        elif t == "quote":
            blocks.append(f"<blockquote>{blk['text']}</blockquote>")
        elif t == "leaderboard":
            intro = f"<p>{blk['intro']}</p>\n        " if blk.get("intro") else ""
            blocks.append(intro + leaderboard_table(b, top=blk.get("top", 3)))
        else:
            raise ValueError(f"unknown block type {t!r} in {p['slug']}")

    blocks.append(f"""<div class="crosslink">
            <div>
                <p class="t">{p['closing']}</p>
                <p class="s">{esc(b['name'])} &mdash; {esc(b['subcategory'])} · {esc(b['domain_name'])}</p>
            </div>
            <a class="button primary" href="{d}benchmarks/{fs}.html">View benchmark →</a>
        </div>""")

    body = "\n\n        ".join(blocks)
    plain_summary = p["summary"].replace("&mdash;", "—")

    html = f"""{head(d, f"{p['title']} | TokenWave AI", plain_summary[:250], f"blog/{p['slug']}.html", og_type="article", published=p["date"])}
{GEN_NOTE}
{header(d, 'blog')}
<article class="detail">
    <div class="detail-hero">
        <div class="detail-image" style="background-image: url('{d}{esc(b['image'])}');" role="img" aria-label="{esc(b['name'])} artwork"></div>
        <div class="detail-head">
            <div class="eyebrow">Research note</div>
            <h1>{esc(p['title'])}</h1>
            <p class="detail-meta">
                <span>{esc(p['date'])}</span>
                <span class="sep">·</span>
                <span>{esc(b['name'])}</span>
                <span class="sep">·</span>
                <span>{read_minutes(p)} min read</span>
            </p>
        </div>
    </div>
    <div class="markdown">

        {body}

        <p class="back-link"><a href="{d}blog.html">&larr; Back to Blog</a></p>
    </div>
</article>
{footer(d)}"""
    write(f"blog/{p['slug']}.html", html)


# ── compare ──────────────────────────────────────────────────────────────────

def build_compare(benches, models):
    coverage = {}
    for b in benches.values():
        for r in b["leaderboard"]:
            mid = r.get("model_id")
            if mid:
                coverage[mid] = coverage.get(mid, 0) + 1

    model_list = []
    for mid, cov in coverage.items():
        info = models.get(mid, {})
        model_list.append({
            "id": mid,
            "name": info.get("name", mid),
            "org": info.get("org", ""),
            "color": info.get("color", "#94a3b8"),
            "coverage": cov,
        })
    model_list.sort(key=lambda m: (-m["coverage"], m["name"].lower()))

    bench_list = []
    for dom in DOMAIN_ORDER:
        for b in sorted((x for x in benches.values() if x["domain"] == dom), key=lambda x: x["name"].lower()):
            direction = "higher"
            for m in b["metrics"]:
                if m["name"] == b.get("leaderboard_metric"):
                    direction = m["direction"]
                    break
            else:
                if b["metrics"]:
                    direction = b["metrics"][0]["direction"]
            bench_list.append({
                "file": file_slug(b["slug"]),
                "name": b["name"],
                "domain": dom,
                "domain_label": DOMAIN_SHORT[dom],
                "subcategory": b["subcategory"],
                "metric": b.get("leaderboard_metric"),
                "dir": direction,
                "scores": {r["model_id"]: r["score"] for r in b["leaderboard"] if r.get("model_id")},
            })

    compare = {"models": model_list, "benchmarks": bench_list}
    write("data/compare.json", json.dumps(compare, indent=1, ensure_ascii=False) + "\n")

    ui = (TPL / "compare_ui.js").read_text(encoding="utf-8")
    bundle = ("/* Generated by tools/build.py — data + UI in one file (no load-order race). */\n"
              f"window.TW_COMPARE = {json.dumps(compare, ensure_ascii=False, separators=(',', ':'))};\n\n{ui}")
    write("static/js/compare-app.js", bundle)

    d = ""
    html = f"""{head(d, "Compare | TokenWave AI", "Select up to 5 models for cross-benchmark comparison across all TokenWave leaderboards.", "compare.html")}
{GEN_NOTE}
{header(d, 'compare')}
<section class="page-header">
    <div class="eyebrow">Compare</div>
    <h1>Line up the models. Keep the axes honest.</h1>
    <p class="page-intro">Select up to 5 models for cross-benchmark comparison. Rows are benchmarks; the best score per row is highlighted. Missing entries mean the model has not been scored there.</p>
</section>

<section class="cmp" id="cmp-root" data-nosnippet>
    <noscript><p class="muted">The comparison tool needs JavaScript. All underlying numbers are on the individual <a href="benchmarks.html">benchmark pages</a>.</p></noscript>
</section>
<script src="static/js/compare-app.js"></script>
{footer(d)}"""
    write("compare.html", html)

    return len(model_list)


# ── seo files ────────────────────────────────────────────────────────────────

def build_seo(benches, posts):
    latest_bench = max(b["at_a_glance"].get("data_updated") or "2026-01-01" for b in benches.values())
    latest_post = max(p["date"] for p in posts)
    latest = max(latest_bench, latest_post)

    urls = [
        ("", latest, "weekly", "1.0"),
        ("benchmarks.html", latest_bench, "weekly", "0.9"),
        ("blog.html", latest_post, "weekly", "0.8"),
        ("compare.html", latest_bench, "weekly", "0.8"),
        ("joinus.html", latest, "monthly", "0.5"),
    ]
    for b in sorted(benches.values(), key=lambda x: file_slug(x["slug"])):
        urls.append((f"benchmarks/{file_slug(b['slug'])}.html",
                     b["at_a_glance"].get("data_updated") or latest_bench, "monthly", "0.7"))
    for p in posts:
        urls.append((f"blog/{p['slug']}.html", p["date"], "monthly", "0.6"))

    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for path, mod, freq, pri in urls:
        lines.append(f"  <url><loc>{SITE}/{path}</loc><lastmod>{mod}</lastmod>"
                     f"<changefreq>{freq}</changefreq><priority>{pri}</priority></url>")
    lines.append("</urlset>")
    write("sitemap.xml", "\n".join(lines) + "\n")

    write("robots.txt", f"User-agent: *\nAllow: /\n\nSitemap: {SITE}/sitemap.xml\n")


# ── main ─────────────────────────────────────────────────────────────────────

def main():
    benches, models, featured, posts, editorial = load()
    post_by_bench = {p["benchmark"]: p for p in posts}

    for b in benches.values():
        build_detail(b, post_by_bench, editorial)
    print(f"benchmarks/: {len(benches)} detail pages ({len(editorial)} with editorial layer)")

    models_tracked = build_compare(benches, models)
    print(f"compare.html + compare-app.js: {models_tracked} models, {len(benches)} benchmarks")

    build_benchmarks_page(benches, featured, models_tracked)
    print("benchmarks.html: featured "
          f"{len(featured)} + full index of {len(benches)}")

    build_blog_list(posts, benches)
    for p in posts:
        build_post(p, benches)
    print(f"blog/: {len(posts)} articles + blog.html")

    build_seo(benches, posts)
    print("sitemap.xml + robots.txt")


if __name__ == "__main__":
    main()
