#!/usr/bin/env python3
"""Build every generated page of tokenwave.ai from data/.

Single sources of truth:
    data/benchmarks/<slug>.json   scraped benchmark records (tools/scrape.py)
    data/models.json              model id -> {name, org, color}
    data/focus_en.json            English overrides for Chinese source fields
    data/careers.json             career tracks -> benchmark slugs + copy
    data/blog/<slug>.json         hand-polished article copy

Outputs:
    benchmarks/<slug>.html  x50       research/<slug>.html
    careers.html                      research.html
    benchmarks.html (redirect)        blog.html (redirect)
    sitemap.xml, robots.txt

data/blog/archive/ holds written-but-unpublished notes; only top-level
data/blog/*.json is published.

Deterministic and idempotent: re-running with unchanged data produces
byte-identical output (verify with `git diff` / checksums).

Run:  python3 tools/build.py
"""

import hashlib
import html as htmlmod
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
TPL = Path(__file__).resolve().parent / "templates"

SITE = "https://tokenwave.ai"

GEN_NOTE = "<!-- Generated by tools/build.py — edit data/ or tools/, not this file. -->"


def asset_v(rel):
    """Short content hash for cache-busting ?v= query strings."""
    return hashlib.md5((ROOT / rel).read_bytes()).hexdigest()[:8]


def asset_url(rel):
    """Return a local asset URL whose query changes when the file changes."""
    return f"{rel}?v={asset_v(rel)}"


V_CSS = asset_v("static/css/style.css")
V_PARTICLES = asset_v("static/js/particles.js")
V_TRANSITION = asset_v("static/js/transition.js")
V_SITE = asset_v("static/js/site.js")
V_HOME = ""  # set in main() after home-data.js is generated


def esc(s):
    return htmlmod.escape(str(s), quote=True)


def fmt_score(v):
    return f"{v:g}" if isinstance(v, (int, float)) else "–"


# ── data loading ─────────────────────────────────────────────────────────────

def load():
    benches = {}
    for f in sorted((DATA / "benchmarks").glob("*.json")):
        d = json.loads(f.read_text(encoding="utf-8"))
        benches[d["slug"]] = d

    focus_en = json.loads((DATA / "focus_en.json").read_text(encoding="utf-8"))
    for slug, over in focus_en.items():
        if slug.startswith("_") or slug not in benches:
            continue
        g = benches[slug]["at_a_glance"]
        if over.get("focus"):
            g["focus"] = over["focus"]
        if over.get("setting"):
            g["setting"] = over["setting"]

    models = json.loads((DATA / "models.json").read_text(encoding="utf-8"))

    careers = json.loads((DATA / "careers.json").read_text(encoding="utf-8"))["careers"]
    assigned = [s for c in careers for s in c["benchmarks"]]
    unknown = set(assigned) - set(benches)
    dupes = {s for s in assigned if assigned.count(s) > 1}
    if unknown or dupes:
        raise SystemExit(f"careers.json error — unknown: {unknown or '{}'}, "
                         f"duplicated: {dupes or '{}'}")

    posts = []
    for f in sorted((DATA / "blog").glob("*.json")):
        posts.append(json.loads(f.read_text(encoding="utf-8")))
    posts.sort(key=lambda p: p["date"], reverse=True)

    research = json.loads((DATA / "research.json").read_text(encoding="utf-8"))
    for f in research["featured"]:
        if f["slug"] not in benches:
            raise SystemExit(f"research.json: unknown featured slug {f['slug']!r}")

    editorial = {}
    ed_dir = DATA / "editorial"
    if ed_dir.exists():
        for f in sorted(ed_dir.glob("*.json")):
            e = json.loads(f.read_text(encoding="utf-8"))
            editorial[e["slug"]] = e

    return benches, models, careers, posts, editorial, research


# ── shared page chrome ───────────────────────────────────────────────────────

def head(depth, title, desc, path, og_type="website", published=None):
    d = depth
    og_extra = ""
    if published:
        og_extra = f'\n    <meta property="article:published_time" content="{published}">'
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{esc(title)}</title>
    <meta name="description" content="{esc(desc)}">

    <meta property="og:type" content="{og_type}">
    <meta property="og:site_name" content="TokenWave AI">
    <meta property="og:title" content="{esc(title)}">
    <meta property="og:description" content="{esc(desc)}">
    <meta property="og:url" content="{SITE}/{path}">
    <meta property="og:image" content="{SITE}/static/images/og-default.png">{og_extra}
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="{esc(title)}">
    <meta name="twitter:description" content="{esc(desc)}">
    <meta name="twitter:image" content="{SITE}/static/images/og-default.png">
    <link rel="canonical" href="{SITE}/{path}">

    <link rel="icon" type="image/svg+xml" href="{d}static/favicon.svg">
    <link rel="icon" type="image/png" sizes="192x192" href="{d}static/favicon-192.png">
    <link rel="apple-touch-icon" href="{d}static/apple-touch-icon.png">
    <link rel="preload" href="{d}static/fonts/IBMPlexSans-Regular.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="preload" href="{d}static/fonts/IBMPlexMono-Regular.woff2" as="font" type="font/woff2" crossorigin>
    <link rel="stylesheet" href="{d}static/css/style.css?v={V_CSS}">
    <!-- Pre-hide page if arriving via full-page transition (must run before first paint) -->
    <script>try{{if(sessionStorage.getItem('tokenwave_transition')==='full'){{document.documentElement.style.opacity='0';}}}}catch(e){{}}</script>
</head>"""


# (id, name) pairs for the Careers hover menu; filled from careers.json in main().
CAREERS_NAV = []




def header(depth, active):
    d = depth
    def nav(href, label, key):
        cls = ' class="active"' if key == active else ""
        return f'<a href="{d}{href}"{cls}>{label}</a>'
    return f"""<body>
    <header class="site-header">
        <div class="container header-content">
            <a class="logo" href="{d}index.html" aria-label="TokenWave AI home">
                <img src="{d}static/images/mark.png" alt="" class="logo-icon">
                <span class="logo-word">TokenWave<span class="ai">AI</span></span>
            </a>
            <nav>
                {nav('index.html', 'Home', 'home')}
                {nav('careers.html', 'Careers', 'careers')}
                {nav('research.html', 'Research', 'research')}
                {nav('joinus.html', 'Join Us', 'joinus')}
            </nav>
        </div>
    </header>
    <main class="container">
"""


def footer(depth):
    d = depth
    return f"""
    </main>
    <footer class="site-footer">
        <div class="container footer-grid">
            <div class="footer-brand">
                <div class="footer-wordmark">TokenWave AI</div>
                <p>Intelligence emerges as tokens flow and communicate, unlocking productivity.</p>
                <p>&copy; 2026 TokenWave AI</p>
            </div>
            <div class="footer-col">
                <div class="h">Site</div>
                <a href="{d}index.html">Home</a>
                <a href="{d}careers.html">Careers</a>
                <a href="{d}research.html">Research</a>
                <a href="{d}joinus.html">Join Us</a>
            </div>
            <div class="footer-col">
                <div class="h">Contact</div>
                <a href="mailto:contact@tokenwave.ai">contact@tokenwave.ai</a>
                <a href="mailto:hr@tokenwave.ai">hr@tokenwave.ai</a>
                <a href="https://x.com/" target="_blank" rel="noopener noreferrer" class="social-link" aria-label="Follow us on X">
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/>
                    </svg>
                </a>
            </div>
        </div>
    </footer>
    <!-- Three.js particle background (bundled locally) -->
    <script src="{d}static/js/three.min.js" defer></script>
    <script src="{d}static/js/particles.js?v={V_PARTICLES}" defer></script>
    <!-- Page transition state machine -->
    <script src="{d}static/js/transition.js?v={V_TRANSITION}" defer></script>
    <!-- Live board data (generated) + reveals, count-ups, meters, marquee -->
    <script src="{d}static/js/home-data.js?v={V_HOME}" defer></script>
    <script src="{d}static/js/site.js?v={V_SITE}" defer></script>
</body>
</html>
"""


def write(rel, content):
    out = ROOT / rel
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")


# ── shared fragments ─────────────────────────────────────────────────────────

def file_slug(slug):
    return slug.replace("_", "-")


BENCHMARK_PAPER_TYPES = {"benchmark", "benchmark_system"}
PAPER_TYPE_LABELS = {
    "benchmark": "Benchmark paper",
    "benchmark_system": "Benchmark & system paper",
    "system": "System paper",
    "model": "Model paper",
    "training": "Training & data paper",
    "data": "Data paper",
}


def is_benchmark_paper(b):
    """Only benchmark papers own a site leaderboard."""
    return b.get("paper_type", "benchmark") in BENCHMARK_PAPER_TYPES


def paper_type_label(b):
    kind = b.get("paper_type", "benchmark")
    return PAPER_TYPE_LABELS.get(kind, kind.replace("_", " ").title())


def leader_of(b):
    lb = b["leaderboard"] if is_benchmark_paper(b) else []
    return lb[0] if lb else None


def bench_meta_line(b):
    lead = leader_of(b)
    bits = [esc(paper_type_label(b))]
    if lead:
        bits.append(f'<span class="lead">Leader &mdash; {esc(lead["model"])} · {fmt_score(lead["score"])}</span>')
    bits.append(esc(b["subcategory"]))
    updated = b["at_a_glance"].get("data_updated")
    if updated:
        bits.append(f"updated {esc(updated)}")
    return '\n                <span class="sep">·</span>\n                '.join(bits)


def card(depth, href, image, meta_html, title, blurb_html):
    return f"""
    <article class="card card-row">
        <div class="card-image" style="background-image: url('{depth}{esc(asset_url(image))}');"></div>
        <div class="card-body">
            <div class="card-meta">
                {meta_html}
            </div>
            <h3><a href="{href}">{esc(title)}</a></h3>
            <p>{blurb_html}</p>
        </div>
    </article>
"""


def leaderboard_table(b, top=None, depth=""):
    metric = b.get("leaderboard_metric") or "Score"
    rows = b["leaderboard"][:top] if top else b["leaderboard"]
    has_date = any(r.get("date") for r in rows)
    # Source provenance stays in the structured data and setting note; the
    # public table focuses on comparable model/score rows.
    show_source = b.get("show_source", False)
    rmax, direction = metric_rmax(b)
    head_cells = f"<th>#</th><th>Model</th><th>{esc(metric)}</th>"
    if show_source:
        head_cells += "<th>Source</th>"
    if has_date:
        head_cells += "<th>Date</th>"
    out = [f"<table class=\"data-table\">\n            <thead>\n                <tr>{head_cells}</tr>\n            </thead>\n            <tbody>"]
    src_label = {"official": "Official", "community": "Community", "self_reported": "Self-reported"}
    for r in rows:
        cls = ' class="lead-row"' if r["rank"] == 1 else ""
        score_cell = fmt_score(r["score"])
        if direction == "higher" and isinstance(r["score"], (int, float)) and rmax > 0:
            w = min(100.0, r["score"] / rmax * 100)
            score_cell += (f'<span class="lb-track"><span class="lb-bar" '
                           f'data-w="{w:.1f}"></span></span>')
        cells = [
            f'<td><span class="rank">{r["rank"]}</span></td>',
            f'<td>{esc(r["model"])}</td>',
            f'<td class="num">{score_cell}</td>',
        ]
        if show_source:
            cells.append(f'<td>{esc(src_label.get(r.get("source"), r.get("source") or "–"))}</td>')
        if has_date:
            cells.append(f'<td class="num">{esc(r.get("date") or "–")}</td>')
        out.append(f"                <tr{cls}>{''.join(cells)}</tr>")
    out.append("            </tbody>\n        </table>")
    return "\n".join(out)


# ── benchmark detail pages ───────────────────────────────────────────────────

# Sticky-TOC scroll spy (plain string — not an f-string — because of the braces)
SCROLLSPY = """<script>
(function () {
    var toc = document.querySelector('.toc');
    if (!toc || !('IntersectionObserver' in window)) return;
    var links = {};
    toc.querySelectorAll('a[href^="#"]').forEach(function (a) {
        links[a.getAttribute('href').slice(1)] = a;
    });
    var io = new IntersectionObserver(function (entries) {
        entries.forEach(function (e) {
            if (!e.isIntersecting) return;
            Object.keys(links).forEach(function (k) { links[k].classList.remove('on'); });
            var l = links[e.target.id];
            if (l) l.classList.add('on');
        });
    }, { rootMargin: '-15% 0px -70% 0px' });
    Object.keys(links).forEach(function (k) {
        var el = document.getElementById(k);
        if (el) io.observe(el);
    });
})();
</script>"""


def build_detail(b, post_by_bench, editorial, career):
    d = "../"
    fs = file_slug(b["slug"])
    ed = editorial.get(b["slug"])
    benchmark_paper = is_benchmark_paper(b)
    desc = (ed["tagline"] + "." if ed and benchmark_paper else
            (b["abstract"][:250].strip() if b["abstract"] else f"{b['name']} on TokenWave AI."))

    actions = []
    if b["links"].get("paper"):
        actions.append(f'<a class="button primary" href="{esc(b["links"]["paper"])}" target="_blank" rel="noopener noreferrer">Paper ↗</a>')
    if b["links"].get("code") and b["links"].get("code") != b["links"].get("paper"):
        actions.append(f'<a class="button" href="{esc(b["links"]["code"])}" target="_blank" rel="noopener noreferrer">Code &amp; Website ↗</a>')
    actions_html = ""
    if actions:
        actions_html = f'\n    <div class="detail-actions">{" ".join(actions)}</div>'

    def paras(texts):
        return "\n        ".join(f"<p>{esc(t)}</p>" for t in texts)

    # (anchor id, TOC title, body html) — TOC and h2 anchors come from this list
    secs = []

    if ed and benchmark_paper:
        secs.append(("overview", "Overview", paras(ed["overview"])))
        secs.append(("why-it-matters", "Why it matters", paras(ed["why"])))
    elif b["abstract"]:
        secs.append(("abstract", "Abstract", f"<p>{esc(b['abstract'])}</p>"))

    if b["contributions"]:
        items = "\n            ".join(f"<li>{esc(c)}</li>" for c in b["contributions"])
        secs.append(("contributions", "Contributions", f"<ul>\n            {items}\n        </ul>"))

    if b["method"]:
        items = "\n            ".join(f"<li>{esc(m)}</li>" for m in b["method"])
        secs.append(("method", "Method &amp; evaluation", f"<ul>\n            {items}\n        </ul>"))

    if b["metrics"]:
        parts = []
        for m in b["metrics"]:
            direction = "Higher is better" if m["direction"] == "higher" else "Lower is better"
            bits = [f"<b>{esc(m['name'])}</b> &mdash; {direction}."]
            if m.get("note"):
                bits.append(esc(m["note"]))
            if m.get("range"):
                bits.append(f"Score range: {esc(m['range'])}.")
            parts.append(f"<p>{' '.join(bits)}</p>")
        secs.append(("metrics", "Evaluation metrics", "\n        ".join(parts)))

    if benchmark_paper and b["leaderboard"]:
        lb_note = f"<p>{esc(b['leaderboard_note'])}</p>\n        " if b.get("leaderboard_note") else ""
        secs.append(("leaderboard", "Leaderboard", f"{lb_note}{leaderboard_table(b)}"))

    if ed and benchmark_paper:
        secs.append(("reading-the-results", "Reading the results", paras(ed["reading"])))

    if b.get("figures"):
        figs = []
        for f in b["figures"]:
            figs.append(
                f'<figure>\n            <img src="{d}{esc(asset_url(f["image"]))}" alt="{esc(f["caption"] or b["name"] + " figure")}" loading="lazy">\n'
                f'            <figcaption>{esc(f["caption"])}</figcaption>\n        </figure>'
            )
        secs.append(("paper-figures", "Figures &amp; tables", "\n        ".join(figs)))

    body_parts = [f'<h2 id="{sid}">{title}</h2>\n        {body}' for sid, title, body in secs]

    post = post_by_bench.get(b["slug"])
    if post:
        body_parts.append(f"""<div class="crosslink">
            <div>
                <p class="t">Read the research note</p>
                <p class="s">{esc(post['title'])}</p>
            </div>
            <a class="button primary" href="{d}research/{post['slug']}.html">Read note →</a>
        </div>""")

    body_sections = "\n\n        ".join(body_parts)

    toc_html = ""
    if len(secs) >= 4:
        toc_links = "\n        ".join(f'<a href="#{sid}">{title}</a>' for sid, title, _ in secs)
        toc_html = f"""
    <nav class="toc" aria-label="On this page">
        <div class="toc-h">On this page</div>
        {toc_links}
    </nav>"""

    tagline_html = (f'\n            <p class="detail-tagline">{esc(ed["tagline"])}.</p>'
                    if ed and benchmark_paper else "")

    stats_html = ""
    if ed and benchmark_paper and ed.get("stats"):
        tiles = "\n        ".join(
            f'<div class="stat-tile"><div class="v">{esc(s["value"])}</div><div class="l">{esc(s["label"])}</div></div>'
            for s in ed["stats"]
        )
        stats_html = f"""
    <div class="stat-grid">
        {tiles}
    </div>
"""

    lead = leader_of(b)
    lead_alt = f"{b['name']} — led by {lead['model']} at {fmt_score(lead['score'])}" if lead else b["name"]

    if career:
        eyebrow = (f'<a class="eyebrow-link" href="{d}careers.html#{career["id"]}">'
                   f'{esc(career["name"])}</a> · {esc(b["subcategory"])}')
        back_link = (f'<a href="{d}careers.html#{career["id"]}">&larr; Back to '
                     f'{esc(career["name"])}</a>')
    else:
        eyebrow = f'Research · {esc(b["subcategory"])}'
        back_link = f'<a href="{d}research.html">&larr; Back to Research</a>'

    html = f"""{head(d, f"{b['name']} | TokenWave AI", desc, f"benchmarks/{fs}.html")}
{GEN_NOTE}
{header(d, 'careers')}
<article class="detail">
    <div class="detail-hero">
        <div class="detail-image" style="background-image: url('{d}{esc(asset_url(b['image']))}');" role="img" aria-label="{esc(lead_alt)}"></div>
        <div class="detail-head">
            <div class="eyebrow">{eyebrow}</div>
            <h1>{esc(b['name'])}</h1>{tagline_html}
            <p class="detail-meta">
                {bench_meta_line(b)}
            </p>{actions_html}
        </div>
    </div>
{stats_html}    <div class="detail-layout">
    <div class="markdown">

        {body_sections}

        <p class="back-link">{back_link}</p>
    </div>{toc_html}
    </div>
</article>
{SCROLLSPY}
{footer(d)}"""
    write(f"benchmarks/{fs}.html", html)


# ── careers page (benchmarks organized by the role they verify) ─────────────

def metric_rmax(b):
    """Upper bound of the primary metric's range, e.g. "[0, 100]" -> 100."""
    direction, rng = "higher", None
    for m in b["metrics"]:
        if m["name"] == b.get("leaderboard_metric"):
            direction, rng = m["direction"], m.get("range")
            break
    else:
        if b["metrics"]:
            direction, rng = b["metrics"][0]["direction"], b["metrics"][0].get("range")
    rmax = 100.0
    if rng:
        m2 = re.search(r",\s*([0-9.]+)\s*\]", rng)
        if m2:
            rmax = float(m2.group(1))
    return rmax, direction


def build_home_data(benches, careers):
    """Real data for the home page: board marquee and frontier chart."""
    rows = []
    for b in benches.values():
        lead = leader_of(b)
        if not lead:
            continue
        rows.append({
            "u": b["at_a_glance"].get("data_updated") or "",
            "n": b["name"],
            "m": lead["model"],
            "s": f'{fmt_score(lead["score"])} {b.get("leaderboard_metric") or "score"}',
            "h": f"benchmarks/{file_slug(b['slug'])}.html",
        })
    rows.sort(key=lambda r: (r["u"], r["n"]), reverse=True)
    rows = [{k: r[k] for k in ("n", "m", "s", "h")} for r in rows[:16]]

    # Flagship board for the frontier chart: the FDE anchor benchmark.
    fb = benches["workflow_gym"]
    frontier = {
        "name": fb["name"],
        "metric": fb.get("leaderboard_metric") or "Score",
        "href": f"benchmarks/{file_slug(fb['slug'])}.html",
        "rows": [{"m": r["model"], "s": r["score"]}
                 for r in fb["leaderboard"][:5] if isinstance(r["score"], (int, float))],
    }

    js = ("/* Generated by tools/build.py — real leaderboard data. */\n"
          f"window.TW_BOARD = {json.dumps(rows, ensure_ascii=False)};\n"
          f"window.TW_FRONTIER = {json.dumps(frontier, ensure_ascii=False)};\n")
    write("static/js/home-data.js", js)
    return len(rows)


def count_models_tracked(benches):
    ids = set()
    for b in benches.values():
        if not is_benchmark_paper(b):
            continue
        for r in b["leaderboard"]:
            if r.get("model_id"):
                ids.add(r["model_id"])
    return len(ids)


STATUS_LABEL = {"certifying": "Current coverage", "next": "Next in line"}


def build_careers_page(benches, careers, editorial):
    d = ""

    rail = "\n        ".join(
        f'<a href="#{c["id"]}"><span class="dot"></span><span class="lbl">{esc(c["name"])}</span></a>'
        for c in careers
    )
    strip = "\n        <span class=\"sep\">/</span>\n        ".join(
        f'<a href="#{c["id"]}">{esc(c["name"])}</a>' for c in careers
    )

    blocks = []
    for i, c in enumerate(careers):
        cards = []
        for slug in c["benchmarks"]:
            b = benches[slug]
            fs = file_slug(slug)
            ed = editorial.get(slug)
            if ed and is_benchmark_paper(b):
                blurb = ed["tagline"] + "."
            else:
                first = (b["abstract"] or "").split(". ")[0]
                blurb = (first + ".") if first else b["name"]
            meta = (f'{esc(paper_type_label(b))} <span class="sep">·</span> '
                    f'{esc(b["subcategory"])}')
            cards.append(f"""            <a class="ev-card" href="benchmarks/{fs}.html">
                <div class="ev-body">
                    <div class="ev-meta">{meta}</div>
                    <h3>{esc(b['name'])}</h3>
                    <p>{esc(blurb)}</p>
                </div>
                <div class="ev-img" style="background-image: url('{esc(asset_url(b['image']))}');"></div>
            </a>""")

        blocks.append(f"""    <div class="career-block rv" id="{c['id']}">
        <div class="career-head">
            <div class="career-meta">
                <span class="career-idx">{i + 1:02d}</span>
                <span class="career-status st-{c['status']}">{STATUS_LABEL[c['status']]}</span>
            </div>
            <h2>{esc(c['name'])}</h2>
            <p class="career-tagline">{esc(c['tagline'])}.</p>
            <p class="career-desc">{esc(c['description'])}</p>
            <p class="career-duties">{esc(c['duties'])}</p>
        </div>
        <div class="career-evidence">
            <div class="evidence-h">{len(c['benchmarks'])} papers and benchmarks</div>
{chr(10).join(cards)}
        </div>
    </div>""")

    desc = ("Benchmarks organized around professional roles in programming, mathematics, "
            "machine learning, and audio/video production.")
    html = f"""{head(d, "Careers | TokenWave AI", desc, "careers.html")}
{GEN_NOTE}
{header(d, 'careers')}
<section class="page-header">
    <div class="eyebrow">Careers</div>
    <h1>Professional roles we evaluate.</h1>
    <p class="page-intro">Each role groups papers and benchmarks around concrete tasks in programming, mathematics, machine learning, and audio/video production.</p>
</section>

<nav class="career-strip" aria-label="Careers on this page">
        {strip}
</nav>

<div class="careers-layout">
    <nav class="rail" aria-label="Careers on this page">
        {rail}
    </nav>
    <section class="career-index">
{chr(10).join(blocks)}
    </section>
</div>
{footer(d)}"""
    write("careers.html", html)


def build_redirect(old_path, new_path, title, note):
    # Preserve inbound links to renamed top-level pages.
    write(old_path, f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{esc(title)} | TokenWave AI</title>
    <meta http-equiv="refresh" content="0; url={new_path}">
    <link rel="canonical" href="{SITE}/{new_path}">
    <meta name="robots" content="noindex">
</head>
<body>
    <p>{note} <a href="{new_path}">{esc(title)}</a>.</p>
</body>
</html>
""")


# ── research notes ───────────────────────────────────────────────────────────

def read_minutes(post):
    words = 0
    for blk in post["body"]:
        for key in ("text",):
            if blk.get(key):
                words += len(blk[key].split())
        for item in blk.get("items", []):
            words += len(item.split())
    words += len(post["summary"].split())
    return max(1, round(words / 200))


def build_research_home(posts, benches, research, editorial):
    d = ""
    # Paper links for plain-name works that exist in data/benchmarks/
    paper_by_name = {b["name"]: b["links"].get("paper")
                     for b in benches.values() if b["links"].get("paper")}

    feats = []
    for i, f in enumerate(research["featured"]):
        b = benches[f["slug"]]
        fs = file_slug(f["slug"])
        ed = editorial.get(f["slug"])
        if ed and is_benchmark_paper(b):
            blurb = ed["tagline"] + "."
        else:
            first = (b["abstract"] or "").split(". ")[0]
            blurb = (first + ".") if first else b["name"]
        stagger = " rv2" if i % 4 in (1, 2) else (" rv3" if i % 4 == 3 else "")
        feats.append(f"""        <a class="rc-card rv{stagger}" href="benchmarks/{fs}.html">
            <div class="rc-img" style="background-image:url('{esc(asset_url(b['image']))}')"></div>
            <div class="rc-body">
                <div class="rc-meta"><span>{esc(f['label'])}</span></div>
                <h3>{esc(b['name'])}</h3>
                <p class="rc-blurb">{esc(blurb)}</p>
            </div>
        </a>""")

    dirs = []
    for i, dr in enumerate(research["directions"]):
        pills = []
        for w in dr["works"]:
            name = w["t"] if isinstance(w, dict) else w
            url = None
            if isinstance(w, dict) and w.get("ax"):
                url = f'https://arxiv.org/abs/{w["ax"]}'
            elif name in paper_by_name:
                url = paper_by_name[name]
            if url:
                pills.append(f'<a class="dl-work dl-link" href="{esc(url)}" '
                             f'target="_blank" rel="noopener noreferrer">{esc(name)}<span class="x">&#8599;</span></a>')
            else:
                pills.append(f'<span class="dl-work">{esc(name)}</span>')
        tags = "\n                ".join(pills)
        dirs.append(f"""        <div class="dl-item rv" id="{dr['id']}">
            <div class="dl-marker" aria-hidden="true"></div>
            <div class="dl-body">
                <div class="dl-head">
                    <span class="dl-idx">{i + 1:02d}</span>
                    <h3>{esc(dr['name'])}</h3>
                </div>
                <p class="dl-blurb">{esc(dr['blurb'])}</p>
                <div class="dl-works">
                {tags}
                </div>
            </div>
        </div>""")

    html = f"""{head(d, "Research | TokenWave AI", "TokenWave research in benchmarks, synthetic data, agents, reinforcement learning, foundation models, and pretraining compute allocation.", "research.html")}
{GEN_NOTE}
{header(d, 'research')}
<section class="page-header">
    <div class="eyebrow">Research</div>
    <h1>Research areas and selected projects.</h1>
    <p class="page-intro">TokenWave works on benchmarks, synthetic data, agents, reinforcement learning, foundation models, and pretraining compute allocation with the M-A-P community.</p>
</section>

<section class="home-section rv" style="padding-top: 26px;">
    <div class="evidence-h">Selected projects</div>
    <div class="feat-grid">
{chr(10).join(feats)}
    </div>
</section>

<section class="home-section rv" style="padding-bottom: 64px;">
    <div class="evidence-h">Research areas</div>
    <div class="dirline">
{chr(10).join(dirs)}
    </div>
</section>
{footer(d)}"""
    write("research.html", html)


def build_post(p, benches, editorial):
    d = "../"
    b = benches[p["benchmark"]]
    fs = file_slug(b["slug"])
    ed = editorial.get(b["slug"])

    def hid(text):
        return re.sub(r"[^a-z0-9]+", "-", re.sub(r"<[^>]+>", "", text).lower()).strip("-")

    toc_entries = []
    blocks = []
    blocks.append(f"<p>{p['summary']}</p>")
    for blk in p["body"]:
        t = blk["type"]
        if t == "p":
            blocks.append(f"<p>{blk['text']}</p>")
        elif t == "h2":
            anchor = hid(blk["text"])
            toc_entries.append((anchor, blk["text"]))
            blocks.append(f'<h2 id="{anchor}">{blk["text"]}</h2>')
        elif t == "ul":
            items = "\n            ".join(f"<li>{i}</li>" for i in blk["items"])
            blocks.append(f"<ul>\n            {items}\n        </ul>")
        elif t == "quote":
            blocks.append(f"<blockquote>{blk['text']}</blockquote>")
        elif t == "leaderboard":
            intro = f"<p>{blk['intro']}</p>\n        " if blk.get("intro") else ""
            blocks.append(intro + leaderboard_table(b, top=blk.get("top", 3)))
        else:
            raise ValueError(f"unknown block type {t!r} in {p['slug']}")

    blocks.append(f"""<div class="crosslink">
            <div>
                <p class="t">{p['closing']}</p>
                <p class="s">{esc(b['name'])} &mdash; {esc(b['subcategory'])} · {esc(b['domain_name'])}</p>
            </div>
            <a class="button primary" href="{d}benchmarks/{fs}.html">View benchmark →</a>
        </div>""")

    body = "\n\n        ".join(blocks)
    plain_summary = p["summary"].replace("&mdash;", "—")

    stats_html = ""
    if ed and ed.get("stats"):
        tiles = "\n        ".join(
            f'<div class="stat-tile"><div class="v">{esc(s["value"])}</div><div class="l">{esc(s["label"])}</div></div>'
            for s in ed["stats"]
        )
        stats_html = f"""
    <div class="stat-grid">
        {tiles}
    </div>
"""

    toc_html = ""
    if len(toc_entries) >= 2:
        toc_links = "\n        ".join(f'<a href="#{a}">{t}</a>' for a, t in toc_entries)
        toc_html = f"""
    <nav class="toc" aria-label="On this page">
        <div class="toc-h">On this page</div>
        {toc_links}
    </nav>"""

    html = f"""{head(d, f"{p['title']} | TokenWave AI", plain_summary[:250], f"research/{p['slug']}.html", og_type="article", published=p["date"])}
{GEN_NOTE}
{header(d, 'research')}
<article class="detail">
    <div class="detail-hero">
        <div class="detail-image" style="background-image: url('{d}{esc(asset_url(b['image']))}');" role="img" aria-label="{esc(b['name'])} artwork"></div>
        <div class="detail-head">
            <div class="eyebrow">Research note</div>
            <h1>{esc(p['title'])}</h1>
            <p class="detail-meta">
                <span>{esc(p['date'])}</span>
                <span class="sep">·</span>
                <span>{esc(b['name'])}</span>
                <span class="sep">·</span>
                <span>{read_minutes(p)} min read</span>
            </p>
        </div>
    </div>
{stats_html}    <div class="detail-layout">
    <div class="markdown">

        {body}

        <p class="back-link"><a href="{d}research.html">&larr; Back to Research</a></p>
    </div>{toc_html}
    </div>
</article>
{SCROLLSPY}
{footer(d)}"""
    write(f"research/{p['slug']}.html", html)


# ── hand-maintained pages: refresh asset fingerprints ────────────────────────

def stamp_static_assets():
    versions = {
        "static/css/style.css": V_CSS,
        "static/js/particles.js": V_PARTICLES,
        "static/js/transition.js": V_TRANSITION,
        "static/js/site.js": V_SITE,
        # generated during this build, so hash at call time
        "static/js/home-data.js": asset_v("static/js/home-data.js"),
    }
    pat = re.compile(r'(static/(?:css|js)/[A-Za-z0-9_.-]+)(\?v=[0-9a-f]+)?')

    def sub(m):
        v = versions.get(m.group(1))
        return f"{m.group(1)}?v={v}" if v else m.group(1)

    for rel in ["index.html", "joinus.html"]:
        f = ROOT / rel
        f.write_text(pat.sub(sub, f.read_text(encoding="utf-8")), encoding="utf-8")


# ── seo files ────────────────────────────────────────────────────────────────

def build_seo(benches, posts):
    latest_bench = max(b["at_a_glance"].get("data_updated") or "2026-01-01" for b in benches.values())
    latest_post = max(p["date"] for p in posts)
    latest = max(latest_bench, latest_post)

    urls = [
        ("", latest, "weekly", "1.0"),
        ("careers.html", latest_bench, "weekly", "0.9"),
        ("research.html", latest_post, "weekly", "0.8"),
        ("joinus.html", latest, "monthly", "0.5"),
    ]
    for b in sorted(benches.values(), key=lambda x: file_slug(x["slug"])):
        urls.append((f"benchmarks/{file_slug(b['slug'])}.html",
                     b["at_a_glance"].get("data_updated") or latest_bench, "monthly", "0.7"))
    for p in posts:
        urls.append((f"research/{p['slug']}.html", p["date"], "monthly", "0.6"))

    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for path, mod, freq, pri in urls:
        lines.append(f"  <url><loc>{SITE}/{path}</loc><lastmod>{mod}</lastmod>"
                     f"<changefreq>{freq}</changefreq><priority>{pri}</priority></url>")
    lines.append("</urlset>")
    write("sitemap.xml", "\n".join(lines) + "\n")

    write("robots.txt", f"User-agent: *\nAllow: /\n\nSitemap: {SITE}/sitemap.xml\n")


# ── main ─────────────────────────────────────────────────────────────────────

def main():
    benches, models, careers, posts, editorial, research = load()
    post_by_bench = {p["benchmark"]: p for p in posts}
    career_of = {slug: c for c in careers for slug in c["benchmarks"]}
    CAREERS_NAV[:] = [(c["id"], c["name"]) for c in careers]

    # Published = benchmarks a career or a published research note points at.
    # Everything else stays in data/ but gets no page.
    publish = set(career_of) | set(post_by_bench) | {f["slug"] for f in research["featured"]}
    pub = {s: benches[s] for s in sorted(publish)}

    global V_HOME
    board_rows = build_home_data(pub, careers)
    V_HOME = asset_v("static/js/home-data.js")
    print(f"static/js/home-data.js: {board_rows} board rows + frontier + careers")

    # Default career context for research-only benchmarks: the first career.
    for b in pub.values():
        build_detail(b, post_by_bench, editorial, career_of.get(b["slug"]))
    print(f"benchmarks/: {len(pub)} detail pages published "
          f"({len(benches) - len(pub)} in data/ unpublished)")

    stale = [f for f in (ROOT / "benchmarks").glob("*.html")
             if f.stem not in {file_slug(s) for s in publish}]
    for f in stale:
        f.unlink()
    if stale:
        print(f"benchmarks/: removed {len(stale)} unpublished pages")

    models_tracked = count_models_tracked(pub)
    build_careers_page(pub, careers, editorial)
    build_redirect("benchmarks.html", "careers.html", "Careers",
                   "The benchmark index now lives on")
    print(f"careers.html: {len(careers)} career(s), "
          f"{models_tracked} models tracked on published boards (+ benchmarks.html redirect)")

    build_research_home(posts, benches, research, editorial)
    for p in posts:
        build_post(p, benches, editorial)
    build_redirect("blog.html", "research.html", "Research",
                   "Our notes moved to")
    print(f"research/: {len(posts)} note pages + research.html (+ blog.html redirect)")

    stamp_static_assets()
    print("index.html + joinus.html: asset fingerprints refreshed")

    build_seo(pub, posts)
    print("sitemap.xml + robots.txt")


if __name__ == "__main__":
    main()
